### ISSUE TITLE
`Save options` button is missing

### ISSUE THREAD

**Issue by mnaoumov** [deathau/markdownload#188]

**Comment by deathau** [comment]
This was changed a while ago to auto save whenever you change something, but I guess it's not entirely clear.

**Comment by mnaoumov** [comment]
@deathau no, it doesn't work 100%

If you just import settings from the file and don't change anything, the imported settings don't take effect

**Comment by deathau** [comment]
Then that's a bug with the import.
Thanks for pointing that out, I've fixed it in https://github.com/deathau/markdownload/commit/a9b505aa425da951a3fbabeeef7eba5cceda7a9e

I've also added a little position:fixed indicator that appears when the data gets saved in https://github.com/deathau/markdownload/commit/1ac4eea1a379ea9348fec8a9f0d5874d39705261

I don't think we need a save button.

**Comment by Flashwalker** [comment]
> Then that's a bug with the import. Thanks for pointing that out, I've fixed it in [a9b505a](https://github.com/deathau/markdownload/commit/a9b505aa425da951a3fbabeeef7eba5cceda7a9e)
> 
> I've also added a little position:fixed indicator that appears when the data gets saved in [1ac4eea](https://github.com/deathau/markdownload/commit/1ac4eea1a379ea9348fec8a9f0d5874d39705261)
> 
> I don't think we need a save button.

Has the fix been realeased to theWeb store?
Because this issue still exist there

**Comment by mnaoumov** [comment]
@Flashwalker , no the author did not update the build since Sep 27. You can compile and install it manually in the meanwhile
